### ISSUE TITLE
Wrongly displayed font on UI when MacType is enabled

### ISSUE THREAD

**Issue by jordanyoong1** [GTANAdam/GDIChromium#10]
![image](https://user-images.githubusercontent.com/40160073/143395039-6d189522-cdb7-447b-8b2c-ec8730c70a56.png)

**Comment by jordanyoong1** [comment]
Ok turns out it's because of my font somehow.

**Comment by wegood9** [comment]
I've encountered the same problem. Could you explain more about which font caused this behavior or how you fixed it?
