### ISSUE TITLE
Building instructions

### ISSUE THREAD

**Issue by monoblaine** [GTANAdam/GDIChromium#14]
First of all, thanks for your efforts, fonts look so much better now!

Could you please add a BUILDING.md document? (Steps, flags, options, etc. necessary to build Chromium from source.)

**Comment by yrhikBober** [comment]
Здравствуйте!
Спасибо за ваш труд!
Будет ли продолжение (обновление) GDIChromium? Или хоты бы есть ли это в планах? 
Спасибо.

**Comment by GTANAdam** [comment]
Greetings!
All the documentations for building chromium are here: https://www.chromium.org/developers/how-tos/get-the-code/
