### ISSUE TITLE
Is there any chance to have a version based on 70?

### ISSUE THREAD

**Issue by v3core** [GTANAdam/GDIChromium#7]
hi,
i know its a weird demand but is there any chance you could build chromium that uses gdi based on version 70.0.3538.110 x64? it would mean the world to me, have a good day...

**Comment by GTANAdam** [comment]
Greetings, any reason why version 70 specifically?

**Comment by v3core** [comment]
its the latest version that has the pre-modern material design theme available, a preference for some users

**Comment by GTANAdam** [comment]
I'm afraid that I don't have enough of the time resource to go back to version 70 and port the GDI patches for it. 
you are always welcome to submit PRs.
